"""report_writer_tool — assembles a structured markdown report from agent outputs."""

import os
from datetime import date, timedelta
from langchain_core.tools import tool


def _weekly_breakdown(forecast_schedule: list[dict]) -> str:
    today = date.today()
    weeks = [
        (today, today + timedelta(days=6)),
        (today + timedelta(days=7), today + timedelta(days=13)),
        (today + timedelta(days=14), today + timedelta(days=20)),
        (today + timedelta(days=21), today + timedelta(days=30)),
    ]
    rows = ["| Week | Projected Outflow | Invoice Count |",
            "|------|------------------|---------------|"]
    for start, end in weeks:
        total = 0.0
        count = 0
        for day in forecast_schedule:
            d = date.fromisoformat(day["date"])
            if start <= d <= end:
                total += float(day["projected_amount"])
                count += len(day.get("invoice_ids", []))
        label = f"{start.strftime('%b %d')}–{end.strftime('%b %d')}"
        rows.append(f"| {label} | ${total:,.0f} | {count} |")
    return "\n".join(rows)


def write_report(
    forecast_schedule: list[dict],
    risk_flags: list[dict],
    discount_opportunities: list[dict],
    chart_path: str,
    output_path: str = "output/forecast_report.md",
) -> str:
    """
    Assemble a CFO-ready markdown report from forecast and risk data.
    Returns the path to the saved report file.
    """
    today = date.today()
    end_date = today + timedelta(days=30)

    total_outflow = sum(float(d["projected_amount"]) for d in forecast_schedule)
    largest_day = max(forecast_schedule, key=lambda x: float(x["projected_amount"]), default={})
    largest_amount = float(largest_day.get("projected_amount", 0))
    largest_date = largest_day.get("date", "N/A")

    total_savings = sum(float(o["potential_savings"]) for o in discount_opportunities)

    lines = [
        "# AP Cash Flow Forecast Report",
        f"**Generated:** {today.isoformat()}",
        f"**Forecast Period:** {today.isoformat()} to {end_date.isoformat()}",
        "",
        "---",
        "",
        "## Executive Summary",
        f"- Total projected outflows (30 days): **${total_outflow:,.0f}**",
        f"- Largest single-day exposure: **${largest_amount:,.0f}** on {largest_date}",
        f"- Early payment discount opportunities: **{len(discount_opportunities)} alerts** (potential savings: ${total_savings:,.2f})",
        f"- High-risk late payment flags: **{len(risk_flags)} alert(s)**",
        "",
        "---",
        "",
        "## Weekly Breakdown",
        _weekly_breakdown(forecast_schedule),
        "",
        "---",
        "",
        "## Risk Flags & Recommendations",
    ]

    # Discount opportunities
    if discount_opportunities:
        lines.append("\n### Discount Opportunities")
        for opp in discount_opportunities:
            lines.append(
                f"- **{opp['invoice_id']}** ({opp['vendor_name']}, ${opp['amount']:,.0f}): "
                f"{opp['discount_pct']*100:.1f}% discount (${opp['potential_savings']:,.2f}) "
                f"if paid by {opp['discount_if_paid_by']} — {opp['days_remaining']} day(s) remaining"
            )
    else:
        lines.append("\n### Discount Opportunities\n- None identified.")

    # Late payment risks
    if risk_flags:
        lines.append("\n### Late Payment Risk")
        for flag in risk_flags:
            lines.append(
                f"- **{flag['invoice_id']}** ({flag['vendor_name']}, ${flag['amount']:,.0f}): "
                f"Vendor reliability {flag['reliability_score']*100:.0f}%, due {flag['due_date']} — "
                f"**{flag['risk_level']} RISK** (potential late fee: ${flag['potential_late_fee']:,.2f})"
            )
    else:
        lines.append("\n### Late Payment Risk\n- No high-risk flags.")

    # Chart
    lines += [
        "",
        "---",
        "",
        "## 30-Day Cash Flow Chart",
        f"![30-Day Cash Flow Forecast]({os.path.basename(chart_path)})",
        "",
        "---",
        "",
        "*Report generated by AP Cash Flow Forecasting Multi-Agent System*",
    ]

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path


@tool
def report_writer_tool(
    forecast_schedule: list[dict],
    risk_flags: list[dict],
    discount_opportunities: list[dict],
    chart_path: str,
    output_path: str = "output/forecast_report.md",
) -> str:
    """Assemble a CFO-ready markdown report from forecast and risk data. Returns the path to the saved report file."""
    return write_report(forecast_schedule, risk_flags, discount_opportunities, chart_path, output_path)
